LIBNAME mydata "/courses/d1406ae5ba27fe300 " access=readonly;
DATA new; set mydata.nesarc_pds;

LABEL TAB12MDX="Tobacco Dependence Past 12 Months"
	  CHECK321="Smoked Cigarettes in Past 12 Months"
	  S3AQ3B1="Usual Smoking Frequency"
	  S3AQ3C1="Usual Smoking Quantity";

/*Set appropriate missing data as needed*/
IF S3AQ3B1=9 THEN S3AQ3B1=.;
IF S3AQ3C1=99 THEN S3AQ3C1=.;

IF S3AQ3B1=1 THEN USFREQMO=30;
ELSE IF S3AQ3B1=2 THEN USFREQMO=22;
ELSE IF S3AQ3B1=3 THEN USFREQMO=14;
ELSE IF S3AQ3B1=4 THEN USFREQMO=5;
ELSE IF S3AQ3B1=5 THEN USFREQMO=2.5;
ELSE IF S3AQ3B1=6 THEN USFREQMO=1;
/*USFREQMO usual smoking days per month
1=once a month or less
2.5=2-3 days per month
5=1-2 days per week 
14=3-4 days per week
22=5-6 days per week
30=everyday*/

NUMCIGMO_EST=USFREQMO*S3AQ3C1;

PACKSPERMONTH=NUMCIGMO_EST/20;

IF PACKSPERMONTH LE 5 THEN PACKCATEGORY=3;
ELSE IF PACKSPERMONTH LE 10 THEN PACKCATEGORY=7;
ELSE IF PACKSPERMONTH LE 20 THEN PACKCATEGORY=15;
ELSE IF PACKSPERMONTH LE 30 THEN PACKCATEGORY=25;
ELSE IF PACKSPERMONTH GT 30 THEN PACKCATEGORY=58;

/*subsetting data to include only past 12 month smokers, age 18-25*/
IF CHECK321=1;
IF AGE LE 25;

PROC SORT; by IDNUM;

PROC ANOVA; CLASS MAJORDEPLIFE;
MODEL NUMCIGMO_EST=MAJORDEPLIFE;
MEANS MAJORDEPLIFE;

PROC ANOVA; CLASS ETHRACE2A;
MODEL NUMCIGMO_EST=ETHRACE2A;
MEANS ETHRACE2A/DUNCAN;

RUN;
